### ISSUE TITLE
US3: Create Header

### ISSUE THREAD

**Issue by falkkreimeier** [falkkreimeier/capstone-project#10]
# Value Statement

As a customer i want to know where i am on every Page.

## Acceptance Criteria 
- App shows the Header with Logo
- Correct styling 

## Subtask 

- [ ] Create a Header Component
- [ ] Add Lakritzel writiing
- [ ] Write Component Tests
- [ ] Add Component to App
- [ ] Add style

## Coplexity
- easy
-
