### ISSUE TITLE
US5: Create a Button with a Story

### ISSUE THREAD

**Issue by falkkreimeier** [falkkreimeier/capstone-project#13]
# Value Statement

As a Customer i want tknow more about Lakritel.

## Acceptance Criteria 
- App shows  a story Picture of Lakritzel
- A Button that leads to the ordering Tool
- Correct styling 
- Show Fotos of Product

## Subtask 

- [ ] Create a new Component with spinning effect
- [ ] Build up a button, that toggles the card
- [ ] Show a Picture of Lakritzel
- [ ] Tell a little Story
- [ ] Write Component Tests
- [ ] Add Component to App
- [ ] Add style

## Coplexity
- high
