### ISSUE TITLE
US9: Add Cocktail recepies

### ISSUE THREAD

**Issue by falkkreimeier** [falkkreimeier/capstone-project#19]
# Value Statement

As a Customer i want to know how can i mix Lakritzel with other Drinks.

## Acceptance Criteria 
- App  has a new Component with recepies for Lakritzel
- Correct styling 

## Subtask 

- [ ] Create a mixedDrinks Component
- [ ] Write the recepies into the Data.json
- [ ] Get the Data from Data.json
- [ ] Write Component Tests
- [ ] Add Component to App
- [ ] Add style

## Coplexity
- easy
