### ISSUE TITLE
US1: List of Products

### ISSUE THREAD

**Issue by falkkreimeier** [falkkreimeier/capstone-project#2]
# Value Statement

As a Customer i want to see a List of Products.

## Acceptance Criteria 
- App shows a list of Products
- Correct styling 
- Show Fotos of Product

## Subtask 

- [ ] Create a Json Data with all assets of the Product.
- [ ]  Get the assets of the products with photos 
- [ ]  Create React App
- [ ] Create Component
- [ ] Use Data from Array 
- [ ] Write Component Tests
- [ ] Add Component to App
- [ ] Add style

## Coplexity
- medium
