### ISSUE TITLE
US10: Add Infos about the person behind the Monster

### ISSUE THREAD

**Issue by falkkreimeier** [falkkreimeier/capstone-project#21]
# Value Statement

As a Customer i want to know more about the People behind the Monster.

## Acceptance Criteria 
- App shows  information about myself
- Correct styling 

## Subtask 

- [ ] Create a new Card Components
- [ ] Picture of me
- [ ] Little motivation Text
- [ ] Interests, Facts, Xing, LinkedIn, Portfolio, Blogtext
- [ ] Write Component Tests
- [ ] Add Component to App
- [ ] Add style

## Coplexity
- medium
