### ISSUE TITLE
US12: add AgeGate

### ISSUE THREAD

**Issue by falkkreimeier** [falkkreimeier/capstone-project#29]
# Value Statement

As a Customer i want to know if the poduct ist for people over 18 only

## Acceptance Criteria 
- App shows an AgeGate
- Correct styling 

## Subtask 

- [ ] build up new components
- [ ] First Component: AgeGate with two buttons
- [ ] Second Component: Card if the Person is not old enough to use the app
- [ ] Write Component Tests
- [ ] Add Component to App
- [ ] Add style

## Coplexity
- medium
