### ISSUE TITLE
US8: Add a Navigation

### ISSUE THREAD

**Issue by falkkreimeier** [falkkreimeier/capstone-project#3]
# Value Statement

As a user i want to navigate through the information.

## Acceptance Criteria 
- App  has Buttons in the to shows more content
- Correct styling 

## Subtask 

- [ ] Create a Footer Component
- [ ] Implement Buttons
- [ ] Write Component Tests
- [ ] Add Component to App
- [ ] Add style

## Coplexity
- medium
