### ISSUE TITLE
US 13: LocalStorage for Age Gate

### ISSUE THREAD

**Issue by falkkreimeier** [falkkreimeier/capstone-project#30]
# Value Statement

As a Customer i don't want to verfify my age, everytime i use the web-App.

## Acceptance Criteria 
- local storage safes the Age answer of the customer
- little smooth animations happens after age verification
- Correct styling 

## Subtask 

- [ ] Bring age verification to local storage 
- [ ] add animation for over18Button an under18Button
- [ ] Add Component to App
- [ ] Add style

## Coplexity
- high
