### ISSUE TITLE
US14: Implement emailjs to the app.

### ISSUE THREAD

**Issue by falkkreimeier** [falkkreimeier/capstone-project#31]
# Value Statement

As a customer i want to order the Products as simple as it can be.

## Acceptance Criteria 
- implement emailjs
- make it easy to use

## Subtask 

- [ ] create an emailjs Account
- [ ] Connect it wirth gmail
- [ ] write a function to send emails
- [ ] implement the function to the ordering onClick function

## Coplexity
- medium
