### ISSUE TITLE
US2: Details of Products

### ISSUE THREAD

**Issue by falkkreimeier** [falkkreimeier/capstone-project#5]
# Value Statement

As a customer i want to see Details of the Product.

## Acceptance Criteria 
- App shows details of the Product
- Correct styling 
- easy to use

## Subtask 

- [ ] Create a Button Component
- [ ] Implement a usestate
- [ ] Write a Button Click Function that toggles the UseState
- [ ] Give the Function into the onClick Event
- [ ] Give the useState into the Element
- [ ] Write Component Tests
- [ ] Add Component to App
- [ ] Add style

## Coplexity
- high
