### ISSUE TITLE
US4: Create a Form to Order

### ISSUE THREAD

**Issue by falkkreimeier** [falkkreimeier/capstone-project#6]
# Value Statement

As a customer i want to Order the Products

## Acceptance Criteria 
- App shows a new Cars
- Correct styling 

## Subtask 

- [ ] Create a card Component
- [ ] Add Phone Number, e-Mail-Adress and PayPal Mail to Card.
- [ ] Write Component Tests
- [ ] Add Component to App
- [ ] Add style

## Coplexity
- easy
